const UserActionTypes = {
    IMPORT_USERLIST_START: 'IMPORT_USERLIST_START',
    IMPORT_USERLIST_SUCCESS: 'IMPORT_USERLIST_SUCCESS',
    IMPORT_USERLIST_FAILURE: 'IMPORT_USERLIST_FAILURE',
    CHANGE_USERINFO_START: 'CHANGE_USERINFO_START',
    CHANGE_USEREINFO_SUCCESS: 'CHANGE_USERINFO_SUCCESS',
    CHANGE_USERINFO_FAILURE:'CHANGE_USERINFO_FAILURE'
}

export default UserActionTypes;