const UserActionTypes = {
    IMPORT_USERLIST_START: 'IMPORT_USERLIST_START',
    IMPORT_USERLIST_SUCCESS: 'IMPORT_USERLIST_SUCCESS',
    IMPORT_USERLIST_FAILURE: 'IMPORT_USERLIST_FAILURE'
}

export default UserActionTypes;